workflows:
  flutter-android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
          
